variables:
  baseName: adb3600513
  resourcegroup: rg-wus2-$(baseName)-prd  
  location: westus2
  kvsreadersgroupoid: b52e4d87-587c-45b5-ada1-9681975cbc81
  kvadminsoid: 47746b00b-f6e4-410d-81f6-8926c7a4e9ae
  
