trigger:
  branches:
    include:
      - devy

  paths:
    include:
      - '*'

variables:
  - template: 'variables/global.yml'
parameters:
- name: evironmentObjects
  type: object
  default:
    - environmentName: 'dev'

stages:
- stage: stg_validate_deploy_bundles
  displayName: 'validate_deploy_bundles'
  jobs:
  - job: j_validate_deploy_bundles
    displayName: 'validate_deploy_bundles'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact Bundle '
      inputs:
        targetPath: $(Pipeline.Workspace)/s/bundle_adb_360
        artifact:   ${{ variables.artifactName }}
    - task: CmdLine@2
      inputs:
        script: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      displayName: 'Install Databricks CLI v 2'
    - task: AzureCLI@2
      displayName: 'validate bundle'
      inputs:
        azureSubscription: 'adb-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd ${{ variables.artifactName }}
          databricks bundle validate

- template: stages/adf_deploy_stage.yml@templates
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}



