resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: feature/databricks
trigger:
  branches:
    include:
      - devy

  paths:
    include:
      - '*'


parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'
variables:
- template: variables/global.yml

stages:
- template: stages/dab_validate_publish_stage.yml@templates
  parameters:
    artifactName: ${{ variables.artifactName }}
    serviceName: ${{ variables.serviceName }}
- template: dab_deploy_env_stage.yml
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}



