trigger:
  branches:
    include:
      - devy

  paths:
    include:
      - '*'


parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'

stages:
- template: dab_vaildate_stage.yml
- template: dab_deploy_stage_env.yml
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}



