trigger:
  branches:
    include:
      - devy

  paths:
    include:
      - '*'

variables:
  - template: 'variables/global.yml'

stages:
- stage: stg_validate_deploy_bundles
  displayName: 'validate_deploy_bundles'
  jobs:
  - job: j_validate_deploy_bundles
    displayName: 'validate_deploy_bundles'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact Bundle '
      inputs:
        targetPath: $(Pipeline.Workspace)/s/bundle_adb_360
        artifact:   ${{ variables.artifactName }}
    - task: CmdLine@2
      inputs:
        script: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      displayName: 'Install Databricks CLI v 2'
    - task: AzureCLI@2
      displayName: 'validate bundle'
      inputs:
        azureSubscription: 'adb-sc'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd ${{ variables.artifactName }}
          databricks bundle validate


- stage: deploy_bundle_dev
  displayName: 'Deploy Bundle to Dev'
  variables:
    - template: 'variables/dev.yml'
    - group: vg${{ variables.env }}adb360
    - name: databricksResourceId
      value: '${{ variables.resourceGroupName }}/providers/Microsoft.Databricks/workspaces/${{ variables.databricsAbrv }}-${{variables.regionAbrv }}${{ variables.serviceName }}${{ variables.serviceIdentifier }}${{ variables.resourceGroupName }}'
   
  jobs:
  - deployment: 
    environment: ${{ variables.env }}
    strategy:
      runOnce:
          deploy:
            steps:
              - task: CmdLine@2
                inputs:
                  script: |
                    cd ${{ variables.artifactName }}
                    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
                displayName: 'Install Databricks CLI v 2'
              - task: AzureCLI@2
                displayName: 'call script to deploy bundle'
                inputs:
                  azureSubscription: 'adb-sc'
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    azureSubscriptionId=$(az account show --query id --output tsv)
                    export DATABRICKS_AZURE_RESOURCE_ID= '/subscriptions/$azureSubscriptionId/${{ variables.databricksResourceId }}'
                    cd ../${{ variables.artifactName }}
                    databricks bundle deploy -t ${{ variables.env }}

  


