resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: feature/databricks
trigger:
  branches:
    include:
      - devy

  paths:
    include:
      - '*'


parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'

stages:
- template: dab_validate_publish_stage.yml@templates
- template: dab_deploy_env_stage.yml
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}



