trigger:
  branches:
    include:
      - devy

  paths:
    include:
      - '*'


parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'

stages:
- template: dab_validate_publish_stage.yml
- template: dab_deploy_env_stage.yml
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}



